version: "3"

services:
  app:
    profiles: ["devcontainer"]
    container_name: car-height-detection-dev
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    stdin_open: true
    tty: true
    environment:
      DEVCONTAINER: 1
    network_mode: host
